export const siteConfig = {
    name: "Wine Rock Sessions",
    title: "Wine Rock Sessions 2027 | Música, vino y montaña en Mendoza",
    description:
        "Wine Rock Sessions vuelve a Lomas del Malbec, Luján de Cuyo, el sábado 27 de marzo de 2027: música en vivo a los pies de la cordillera, feria de vinos y experiencias gastronómicas.",
    url: "https://winerock.vercel.app",
    ogImage: "/images/logos/logo.png",
    keywords: [
        "Wine Rock Sessions",
        "Wine Rock Mendoza",
        "festival de música Mendoza",
        "vino y música",
        "Lomas del Malbec",
        "Luján de Cuyo",
        "festival de vino Argentina",
    ],
    event: {
        name: "Wine Rock Sessions 2027",
        startDate: "2027-03-27",
        venue: "Lomas del Malbec",
        address: "Ruta 86, C. 7 s/n",
        postalCode: "M5505",
        locality: "Luján de Cuyo",
        region: "Mendoza",
        geo: { lat: -33.199508, lng: -68.9673263 },
        country: "AR",
        organizers: ["En Vivo Producciones", "Produce Crack Mendoza"],
        lineup: ["Ratones Paranoicos", "Catupecu Machu", "Estelares"],
    },
} as const;
